### ISSUE TITLE
Tmux crashing with "[lost server]"

### ISSUE THREAD

**Issue by christoomey** [christoomey/vim-tmux-runner#1]
Occasionally when moving quickly through a sequence of commands, tmux will crash with the message "[lost server]"

Seems like others have seen this, documented [here](https://github.com/mxcl/homebrew/issues/4058) in homebrew repo

Seems like this is related to tmux, not VTR, but either way concerning.

**Comment by SolitaryCipher** [comment]
I am getting this issue with cygwin on windows. I will post tomorrow with more documentation on what exactly is happening.
