### ISSUE TITLE
Sending custom commands using VtrSendCommandToRunner method

### ISSUE THREAD

**Issue by yuujay** [christoomey/vim-tmux-runner#102]
I am trying to write some custom methods that would send some commands to the runner pane. I am making use of the `VtrSendCommandToRunner` command to send.

The issue that I am seeing is I am unable to send interpolated/concatenated strings as an argument to the runner.

```vimscript
function! ExecuteCurrentSpecFile()
   let fileName = @%
   VtrSendCommandToRunner 'bundle exec rspec '.l:fileName
endfunction
```

The function above sends `bundle exec rspec .l:fileName` as a string instead of something like `bundle exec rspec spec/unit/model/controller.rb`

Is there a different way to approach this?

**Comment by christoomey** [comment]
`VtrSendCommandToRunner` is a vim command and thus a little tricky to work with as you're trying, but there's also a function version provide for this sort of usage:

``` vim
function! ExecuteCurrentSpecFile()
  call VtrSendCommand('bundle exec rspec ' . @%)
endfunction
```

Hope that helps! I'm going to close this issue now as I think that should cover your usage, but feel free to comment or reopen if you think I missed anything.

**Comment by yuujay** [comment]
This fits my need. Thanks Chris!
