### ISSUE TITLE
No default value for VtrAutomaticReattachByName

### ISSUE THREAD

**Issue by arashm** [christoomey/vim-tmux-runner#108]
After the last commit, without explicitly adding `let g:VtrAutomaticReattachByName = 0` in the config, I get an error when running the tests using `vim-test` plugin.

```
Error detected while processing function test#run[27]..test#execute[22]..test#shell[19]..test#strategy#vtr[1]..VtrSendCommand[5]..<SNR>36_SendCommandToRunner[1]..<SNR>36_EnsureRunnerPane:
line    3:
E121: Undefined variable: g:VtrAutomaticReattachByName
```

**Comment by christoomey** [comment]
Hey @arashm, sorry about that! I've just pushed a commit that should resolve this. Mind pulling master and confirming if that works for you?

**Comment by arashm** [comment]
Works again! Thank you!
