### ISSUE TITLE
No new pane is being created

### ISSUE THREAD

**Issue by aaronmcadam** [christoomey/vim-tmux-runner#41]
Hi, according to the documentation, `VtrSendCommandToRunner` should open a new runner pane. However, I just keep on seeing the error `VTR: No runner pane attached.` Am I missing something?

**Comment by aaronmcadam** [comment]
I should also mention that I'm trying to use `vim-spec-runner`, I've configured it like this:
`let g:spec_runner_dispatcher = 'VtrSendCommandToRunner("{command}")'`

**Comment by christoomey** [comment]
Hey @aaronmcadam, short version is you can switch your spec-runner configuration to:

``` vim
let g:spec_runner_dispatcher = "VtrSendCommand! {command}"
```

Longer version is you happened to catch me in the midst of a large refactoring, and as part of it I've removed the implicit opening of a runner pane.

This functionality (creating a pane if one does not exist) has been made explicit via "bang" versions of the commands. So `:VtrSendCommandToRunner` will present the warning you listed as it expects an existing runner pane, and ` `:VtrSendCommandToRunner!` will create one if it doesn't exist.

Hope this covers your issue. Please reopen or comment if you still hit the issue. I'll be updating the docs very soon to avoid this for future users. Thanks for reporting.

**Comment by aaronmcadam** [comment]
Brilliant, thanks for the quick reply @christoomey!
