### ISSUE TITLE
Off by one error in runner_pane with base-index 1 in tmux

### ISSUE THREAD

**Issue by aaronmcadam** [christoomey/vim-tmux-runner#42]
The following is a common-ish setting amongst tmux users I've seen:

```
# Start tab numbering at 1
set -g base-index 1
set-window-option -g pane-base-index 1
```

Using `VtrSendCommand!`, a vim error flashes up (it goes away too quickly for me to read) and a pane gets opened, but the command doesn't get sent.

For now I've just commented out my setting and it's not a deal breaker, but is there an undocumented way to configure the base-index for panes?

**Comment by christoomey** [comment]
Hey @aaronmcadam, thanks for reporting. I must have something hard coded in the attach code which is causing this. Should be easy to fix once I dig in, but for now I think disabling the setting for now is your best option.

**Comment by christoomey** [comment]
@aaronmcadam I just pushed up a fix for this bug that should work with either zero based, or 1 based pane indexes. Can you pull down and test out to confirm?

**Comment by aaronmcadam** [comment]
@christoomey I can confirm the latest `master` is has fixed this. Thanks so much! :smile:
