### ISSUE TITLE
VtrSendLinesToRunner Python whitespace issue

### ISSUE THREAD

**Issue by wolfascu** [christoomey/vim-tmux-runner#63]
I have written the following Python snippet:

```python
def hello():
    print "Hello, world!"
```

When I use *VtrSendLinesToRunner* to send it to a tmux pane running a Python REPL, I get this error:

```
>>> def hello():
... print "Hello, world!"
  File "<stdin>", line 2
    print "Hello, world!"
        ^
IndentationError: expected an indented block
>>> 
```

**Comment by christoomey** [comment]
Hi @wolfascu, Python considers leading white space / indentation as important. By default this plugin strips the white space, but there are a few settings described [here](https://github.com/christoomey/vim-tmux-runner/blob/master/README.md#python-notes) that should make it work for Python code.

**Comment by wolfascu** [comment]
Thanks a lot for the answer!
And sorry I missed this explanation that was straight in the README file. :blush:
