### ISSUE TITLE
bundles vs bundle

### ISSUE THREAD

**Issue by jShaf** [christoomey/vim-tmux-runner#74]
Your README had me installed your plugin into bundles/ when it should be bundle/ that pathogen expects. I had to move your plugin before it works. Lost an hour on this, hah. Anyways, thanks for the plugin!

**Comment by christoomey** [comment]
Hi  @jShaf, sorry for the lost time, but glad you're enjoying the plugin otherwise! I've just pushed 5ba24952c9d4639f0b2369658bb26feb7b29bce2 which updates the README to hopefully avoid future issues for others.
