### ISSUE TITLE
VtrSendCommandToRunner requires bang to open a runner

### ISSUE THREAD

**Issue by anhari** [christoomey/vim-tmux-runner#80]
Hey Chris, I was trying to use `VtrSendCommandToRunner` in some leader keys to open rails console, run migrations, etc., but I think only the bang version of this command will open/attach a runner if one doesn't exist.

I can push a PR with an updated readme/help file if needed, but I'm not sure if this is working as intended.

  I'm using neovim v0.2.0.

**Comment by christoomey** [comment]
Hi @anhari, this is working as intended, although not as documented. The workflow as I've designed it is any of:

- `VtrOpenRunner` to explicitly open and attach to a runner, then `VtrSendCommandToRunner` to send
- `VtrAttachRunner` to attach to an existing pane, then `VtrSendCommandToRunner` to send
- `VtrSendCommandToRunner!` to send (creating a pane as neccesary).

I prefer the explicit workflow and pane creation / attachment, and thus `VtrSendCommandToRunner` behaves the way it does, but `VtrSendCommandToRunner!` was introduced to handle the case of wanting a runner to be created.

I'll keep this issue open as a reminder to myself to update the docs to match the above.

**Comment by jerri** [comment]
Please update the documentation as soon as possible. I was searching for quite some time now to understand why the command wasn't running. The bang requirement is nowhere documentation, as far as I saw.
