### ISSUE TITLE
Workflow question

### ISSUE THREAD

**Issue by iamarmanjon** [christoomey/vim-tmux-runner#87]
I saw last time your upcase tmux course. And I'm reviewing it right now. I want to incorporate your `vim-tmux-runner` plugin with the `vim-rspec`. It works fine UNTIL i close the tmux pane where the test just run, and when I tried to run again, it looks for a pane. I was expecting that it will just create one again like it did the first time.

Because right now, if I close the tmux pane. When I need to add a test again I need to
1. Create a new tmux split
2. Go back to vim, do `:VtrAttachToPane`
3. Then I can run a test again.

I might miss the instruction on the course for this. Please help :)

**Comment by christoomey** [comment]
Hi AJ, unfortunately the workflow you’re describing is not currently supported by the plugin. It is certainly possible, but the commands currently expect the runner pane to remain available.

Likely the best option for right now would be to use the VtrKillRunner command when you want to dismiss the runner pane. By using that the plugin will be aware that the runner pane is closed and will open a new one when you next run VtrSendCommand! (Note the ! at the end of the command which adds the “open a pane if needed” beahavior). I’m going to close this now as the above is the best option for the current situation, and the altered pane opening behavior is better captured by other issues, but please feel free to comment ore reopen if you think I missed something.
